### ISSUE TITLE
Warning: SCENE3D?

### ISSUE THREAD

**Issue by rubyFeedback** [jruby/jrubyfx#129]
When running the demo, I get:

"WARNING: System can't support ConditionalFeature.SCENE3D"

Not sure if this is from jrubyfx or JavaFX. Either way, could more information be
shown in this regard? I downloaded JavaFX from the official sources, using the
SDK. Not sure what I need for SCENE3D or if it is important.

**Comment by byteit101** [comment]
This is a JavaFX warning as you are probably using open-source graphics drivers on Linux. https://stackoverflow.com/questions/30288837/warning-system-cant-support-conditionalfeature-scene3d-vmware-ubuntu suggests that `-J-Dprism.forceGPU=true` or `ENV_JAVA['prism.forceGPU'] = 'true'` should work

SCENE3D is used for any 3d objects on your scenegraph. You are stuck in 2d otherwise
